package ABD_Libros;

import ABD_Alumnos.*;
import java.awt.event.MouseListener;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author 2DAM - Judit
 */
public class DlgLibros extends javax.swing.JDialog {

    public DlgLibros(java.awt.Frame parent, boolean modal, ClaseEventosLibros cleventos) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        jBIniciar.addActionListener(cleventos);
        jBAnterior.addActionListener(cleventos);
        jBSiguiente.addActionListener(cleventos);
        jBAlta.addActionListener(cleventos);
        jBBajas.addActionListener(cleventos);
        jBBuscar.addActionListener(cleventos);

        jTablaLibros.addMouseListener(cleventos);
        jBInformeAlu.addActionListener(cleventos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPnDatos = new javax.swing.JPanel();
        TxtEditorial = new javax.swing.JTextField();
        jLbEditorial = new javax.swing.JLabel();
        jLbTitulo = new javax.swing.JLabel();
        TxtTitulo = new javax.swing.JTextField();
        jLbAsignatura = new javax.swing.JLabel();
        TxtAsignatura = new javax.swing.JTextField();
        jLbAutor = new javax.swing.JLabel();
        TxtAutor = new javax.swing.JTextField();
        jLbCodigo = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLbEstado = new javax.swing.JLabel();
        TxtEstado = new javax.swing.JTextField();
        jPnBotones = new javax.swing.JPanel();
        jBAnterior = new javax.swing.JButton();
        jBAlta = new javax.swing.JButton();
        jBSiguiente = new javax.swing.JButton();
        jBBajas = new javax.swing.JButton();
        jBIniciar = new javax.swing.JButton();
        jPnInforme = new javax.swing.JPanel();
        jBInformeAlu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaLibros = new javax.swing.JTable();
        BtnVolver = new javax.swing.JButton();
        jLbBuscar = new javax.swing.JLabel();
        textoABuscar = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();

        jLabel1.setOpaque(true);
        jLabel1.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPnDatos.setBackground(new java.awt.Color(0, 0, 255));
        jPnDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLbEditorial.setForeground(new java.awt.Color(255, 255, 255));
        jLbEditorial.setText("Editorial:");

        jLbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLbTitulo.setText("Título:");

        jLbAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        jLbAsignatura.setText("Asignatura:");

        jLbAutor.setForeground(new java.awt.Color(255, 255, 255));
        jLbAutor.setText("Autor:");

        jLbCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLbCodigo.setText("Código:");

        jLbEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLbEstado.setText("Estado:");

        javax.swing.GroupLayout jPnDatosLayout = new javax.swing.GroupLayout(jPnDatos);
        jPnDatos.setLayout(jPnDatosLayout);
        jPnDatosLayout.setHorizontalGroup(
            jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TxtAsignatura, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLbAutor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TxtAutor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TxtTitulo)
                        .addGroup(jPnDatosLayout.createSequentialGroup()
                            .addGroup(jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLbEditorial)
                                .addComponent(TxtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPnDatosLayout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(jLbCodigo))
                                .addGroup(jPnDatosLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLbTitulo)
                    .addComponent(jLbAsignatura)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnDatosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLbEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnDatosLayout.setVerticalGroup(
            jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbEditorial)
                    .addComponent(jLbCodigo))
                .addGap(7, 7, 7)
                .addGroup(jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigo)
                    .addComponent(TxtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLbAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbAsignatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbEstado))
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPnBotones.setBackground(new java.awt.Color(0, 0, 255));
        jPnBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBAnterior.setText("Anterior");

        jBAlta.setText("Altas");

        jBSiguiente.setText("Siguiente");

        jBBajas.setText("Bajas");

        jBIniciar.setText("Iniciar");

        javax.swing.GroupLayout jPnBotonesLayout = new javax.swing.GroupLayout(jPnBotones);
        jPnBotones.setLayout(jPnBotonesLayout);
        jPnBotonesLayout.setHorizontalGroup(
            jPnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotonesLayout.createSequentialGroup()
                .addGroup(jPnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnBotonesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBBajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPnBotonesLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jBIniciar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPnBotonesLayout.setVerticalGroup(
            jPnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBIniciar)
                .addGap(17, 17, 17)
                .addGroup(jPnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAnterior)
                    .addComponent(jBSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAlta)
                    .addComponent(jBBajas))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPnInforme.setBackground(new java.awt.Color(0, 0, 255));
        jPnInforme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generar informe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPnInforme.setForeground(new java.awt.Color(255, 255, 255));

        jBInformeAlu.setText("Alumnos");

        javax.swing.GroupLayout jPnInformeLayout = new javax.swing.GroupLayout(jPnInforme);
        jPnInforme.setLayout(jPnInformeLayout);
        jPnInformeLayout.setHorizontalGroup(
            jPnInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnInformeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jBInformeAlu)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPnInformeLayout.setVerticalGroup(
            jPnInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnInformeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBInformeAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTablaLibros.setBackground(new java.awt.Color(162, 195, 227));
        jTablaLibros.setModel(jTablaLibros.getModel());
        jScrollPane1.setViewportView(jTablaLibros);

        BtnVolver.setText("Volver al menú");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jLbBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbBuscar.setText("Buscar:");

        textoABuscar.setForeground(new java.awt.Color(153, 153, 153));
        textoABuscar.setToolTipText("");

        jBBuscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscar))
                    .addComponent(BtnVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPnBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPnInforme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbBuscar)
                    .addComponent(textoABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPnDatos.getAccessibleContext().setAccessibleName("Datos del libro:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextField TxtAsignatura;
    private javax.swing.JTextField TxtAutor;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtEditorial;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.JButton jBAlta;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBBajas;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBInformeAlu;
    private javax.swing.JButton jBIniciar;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbAsignatura;
    private javax.swing.JLabel jLbAutor;
    private javax.swing.JLabel jLbBuscar;
    private javax.swing.JLabel jLbCodigo;
    private javax.swing.JLabel jLbEditorial;
    private javax.swing.JLabel jLbEstado;
    private javax.swing.JLabel jLbTitulo;
    private javax.swing.JPanel jPnBotones;
    private javax.swing.JPanel jPnDatos;
    private javax.swing.JPanel jPnInforme;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTablaLibros;
    private javax.swing.JTextField textoABuscar;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtAsignatura() {
        return TxtAsignatura;
    }

    public void setTxtAsignatura(JTextField TxtAsignatura) {
        this.TxtAsignatura = TxtAsignatura;
    }

    public JTextField getTxtAutor() {
        return TxtAutor;
    }

    public void setTxtAutor(JTextField TxtAutor) {
        this.TxtAutor = TxtAutor;
    }

    public JTextField getTxtCodigo() {
        return TxtCodigo;
    }

    public void setTxtCodigo(JTextField TxtCodigo) {
        this.TxtCodigo = TxtCodigo;
    }

    public JTextField getTxtEditorial() {
        return TxtEditorial;
    }

    public void setTxtEditorial(JTextField TxtEditorial) {
        this.TxtEditorial = TxtEditorial;
    }

    public JTextField getTxtEstado() {
        return TxtEstado;
    }

    public void setTxtEstado(JTextField TxtEstado) {
        this.TxtEstado = TxtEstado;
    }

    public JTextField getTxtTitulo() {
        return TxtTitulo;
    }

    public void setTxtTitulo(JTextField TxtTitulo) {
        this.TxtTitulo = TxtTitulo;
    }

    public JTextField getTextoABuscar() {
        return textoABuscar;
    }

    public void setTextoABuscar(JTextField textoABuscar) {
        this.textoABuscar = textoABuscar;
    }
}
