/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prestamos;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author 2DAM - Judit
 */
public class DlgPrestamos extends javax.swing.JDialog {

    /**
     * Creates new form DlgPrestamos
     */
    public DlgPrestamos(java.awt.Frame parent, boolean modal, ClaseEventosPres cleventos) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        BtnAgregar.addActionListener(cleventos);
        BtnBajas.addActionListener(cleventos);
        BtnBuscar.addActionListener(cleventos);
        BtnCerrar.addActionListener(cleventos);
        BtnEditarMovi.addActionListener(cleventos);
        BtnQuitar.addActionListener(cleventos);
        BtnSiguiente.addActionListener(cleventos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TxtNombreAlu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtApellido1Alu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtApellido2Alu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtDniAlu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtRegistro = new javax.swing.JTextField();
        movPanel = new javax.swing.JPanel();
        movScrollPane = new javax.swing.JScrollPane();
        TablaMovimientos = new javax.swing.JTable();
        BtnAgregar = new javax.swing.JButton();
        BtnEditarMovi = new javax.swing.JButton();
        BtnQuitar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnSiguiente = new javax.swing.JButton();
        BtnBajas = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Primer apellido:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Segundo apellido:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registro:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtDniAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(TxtNombreAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtApellido1Alu, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(TxtApellido2Alu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TxtNombreAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtApellido1Alu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtApellido2Alu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDniAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        movPanel.setBackground(new java.awt.Color(102, 51, 255));
        movPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prestamos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        movPanel.setForeground(new java.awt.Color(255, 255, 255));

        TablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        movScrollPane.setViewportView(TablaMovimientos);

        BtnAgregar.setText("Agregar");

        BtnEditarMovi.setText("Editar");

        BtnQuitar.setText("Quitar");

        javax.swing.GroupLayout movPanelLayout = new javax.swing.GroupLayout(movPanel);
        movPanel.setLayout(movPanelLayout);
        movPanelLayout.setHorizontalGroup(
            movPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                .addGroup(movPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnEditarMovi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        movPanelLayout.setVerticalGroup(
            movPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movPanelLayout.createSequentialGroup()
                .addGroup(movPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(movPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAgregar)
                        .addGap(13, 13, 13)
                        .addComponent(BtnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEditarMovi)
                        .addGap(49, 49, 49))
                    .addComponent(movScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnSiguiente.setText("Siguiente");

        BtnBajas.setText("Bajas");

        BtnBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(BtnSiguiente)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnSiguiente))
                .addGap(18, 18, 18)
                .addComponent(BtnBajas)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        BtnCerrar.setText("Cerrar Ventana");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconAlumnos.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCerrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel6)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(movPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCerrar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBajas;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnEditarMovi;
    private javax.swing.JButton BtnQuitar;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JTable TablaMovimientos;
    private javax.swing.JTextField TxtApellido1Alu;
    private javax.swing.JTextField TxtApellido2Alu;
    private javax.swing.JTextField TxtDniAlu;
    private javax.swing.JTextField TxtNombreAlu;
    private javax.swing.JTextField TxtRegistro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel movPanel;
    private javax.swing.JScrollPane movScrollPane;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregar() {
        return BtnAgregar;
    }

    public void setBtnAgregar(JButton BtnAgregar) {
        this.BtnAgregar = BtnAgregar;
    }

    public JButton getBtnBajas() {
        return BtnBajas;
    }

    public void setBtnBajas(JButton BtnBajas) {
        this.BtnBajas = BtnBajas;
    }

    public JButton getBtnBuscar() {
        return BtnBuscar;
    }

    public void setBtnBuscar(JButton BtnBuscar) {
        this.BtnBuscar = BtnBuscar;
    }

    public JButton getBtnCerrar() {
        return BtnCerrar;
    }

    public void setBtnCerrar(JButton BtnCerrar) {
        this.BtnCerrar = BtnCerrar;
    }

    public JButton getBtnEditarMovi() {
        return BtnEditarMovi;
    }

    public void setBtnEditarMovi(JButton BtnEditarMovi) {
        this.BtnEditarMovi = BtnEditarMovi;
    }

    public JButton getBtnQuitar() {
        return BtnQuitar;
    }

    public void setBtnQuitar(JButton BtnQuitar) {
        this.BtnQuitar = BtnQuitar;
    }

    public JButton getBtnSiguiente() {
        return BtnSiguiente;
    }

    public void setBtnSiguiente(JButton BtnSiguiente) {
        this.BtnSiguiente = BtnSiguiente;
    }

    public JTable getTablaMovimientos() {
        return TablaMovimientos;
    }

    public void setTablaMovimientos(JTable TablaMovimientos) {
        this.TablaMovimientos = TablaMovimientos;
    }

    public JTextField getTxtApellido1Alu() {
        return TxtApellido1Alu;
    }

    public void setTxtApellido1Alu(JTextField TxtApellido1Alu) {
        this.TxtApellido1Alu = TxtApellido1Alu;
    }

    public JTextField getTxtApellido2Alu() {
        return TxtApellido2Alu;
    }

    public void setTxtApellido2Alu(JTextField TxtApellido2Alu) {
        this.TxtApellido2Alu = TxtApellido2Alu;
    }

    public JTextField getTxtDniAlu() {
        return TxtDniAlu;
    }

    public void setTxtDniAlu(JTextField TxtDniAlu) {
        this.TxtDniAlu = TxtDniAlu;
    }

    public JTextField getTxtNombreAlu() {
        return TxtNombreAlu;
    }

    public void setTxtNombreAlu(JTextField TxtNombreAlu) {
        this.TxtNombreAlu = TxtNombreAlu;
    }

    public JTextField getTxtRegistro() {
        return TxtRegistro;
    }

    public void setTxtRegistro(JTextField TxtRegistro) {
        this.TxtRegistro = TxtRegistro;
    }
    
    
}
